### ISSUE TITLE
Show a photo of the person

### ISSUE THREAD

**Issue by jsyrjala** [NitorCreations/nversary#11]
Photos are nowdays available for most of the people.
- See example how office posse does it with Outlook.
- As a fallback you could use Slack avatar image.

Also there are goat images for those who do not have photos available ;)

**Comment by xkr47** [comment]
we need gravatar.nitor.zone :)

**Comment by gmokki** [comment]
We already have it. The url is a bit long, but this works (with any nitor.zone domain):
https://gravatar.nitor.zone/graph/sites/nitorgroupfi.sharepoint.com,00059e1e-67d9-4ed8-8890-f921ea8497c2,099ac5b2-2b19-4263-abb7-a521b78a4e1a/drive/root:/Visuaalinen%20ilme/Henkil%C3%B6kuvat/Profile%20Pictures/Web/Profile_blue_cropped/Mikko_Tiihonen_profile_blue_cropped.jpg:/thumbnails/0/large/content

**Comment by gmokki** [comment]
The o365 self-image is https://gravatar.dev.nitor.zone/graph/me/photos/360x360/$value - or if you know the target person uid you can fetch it with https://graphdemo.dev.nitor.zone/graph/users/cc528f5b-2437-49e0-9988-29b8b3511251/photos/360x360/$value
But I would recommend to use the first link with official photos. Much easier to recognize someone than from funny random photos people use on slack/o365

**Comment by xkr47** [comment]
first link = the one you mentioned in your first comment?

**Comment by jsyrjala** [comment]
I think that the url you put to the slack message should be publicly available, or at least available for Slack servers.

**Comment by gmokki** [comment]
Yes, I recommend the first link from the first comment, pointing to sharepoint through graph api.
I think quite often one can share links to private images or and only the client tries to resolve them? But if bot needs to embed a picture then it needs to (pre) fetch them itself?

**Comment by ketola** [comment]
I thought of one way of implementing this:
- Currently, the data file that contains the info about the employees is included in the project during build / deploy. The file could instead be read from an s3 bucket.
- Data file is currently created by copy-pasting the people.js script to browser console on Contacts page and the output is included in the build. Instead of this, there could be another lambda that generates the data file to the s3 bucket. The lambda would also generate the pictures to a location where slack can access them when posting messages and include the url in the data.

This way the data file generation would be automatic and nversary would remain independent of the way the data is generated.

**Comment by jsyrjala** [comment]
I think that you can upload images to Slack and then refer to them in messages. This way you don't have to have a server that hosts images for Slack

**Comment by jsyrjala** [comment]
Fixed  via https://github.com/NitorCreations/nversary/pull/28
