### ISSUE TITLE
nversary showed a future anniversary

### ISSUE THREAD

**Issue by tjouni** [NitorCreations/nversary#16]
On january 14th nversary congratulated a person for their anniversary which is on the 16th. I still haven't gotten mine even though I started on the 7th.

**Comment by ketola** [comment]
That's actually on purpose. If you look at the comments where the date gets selected: https://github.com/NitorCreations/nversary/blob/master/service/AnniversaryService.ts#L29
You'll see that it attempts to find the closest day in the month for the message, and it can be in the future too. When I was thinking about this, I thought that it's relevant to send the congratulation message during the month when your work anniversary is (not on the correct day as it's not like a birthday), and it also helps to divide the messages so that there is not a flood of messages on one day and silence on another and then everyone gets the same attention.

**Comment by jsyrjala** [comment]
Works as planned
